import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "../components/header/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Masaki",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-gray-50 bg-gray-900`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
